apiVersion: v1
kind: Service
metadata:
  name: test-angular-service
  namespace: test-angular
spec:
  selector:
    app: test-angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer